desc = "Well-behaved and performant interpolation through points in 2D, 3D .. ManyD."
keywords = ["Catmull-Rom", "spline", "cubic", "interpolation", "centripetal"]
name = "CatmullRom"
uuid = "5b5b35a2-003c-5b99-bc04-a964994dd816"
repo = "https://github.com/JeffreySarnoff/CatmullRom.jl.git"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
license = "MIT"
version = "v0.3.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[targets]
test = ["Test", "Polynomials"]

[compat]
Polynomials = "0"
MacroTools  = "0"
LoopVectorization = "0"
Tullio = "0"
StructArrays = "0"
StaticArrays = "0"
julia = "1.5"
